default_settings: &default_settings
  adapter: mysql
  encoding: utf8
  pool: 5
  username: root
  password: 
  # socket: /tmp/mysql.sock

development:
  <<: *default_settings
  database: prehistoric_pets_development

test:
  <<: *default_settings
  database: prehistoric_pets_test

production:
  <<: *default_settings
  database: prehistoric_pets_production
  password: _78_vette