--- 
- products_show_get_public: 
    :format: image/jpeg
    :method: :get
    :action: show
    :controller: products
    :is_public: true
    :models: 
    - Product: 
      - :is_active
      - :price
      - :description
      - :permalink
      - :name
      - :created_at
      - :id
      - :scientific_name
    - Order: 
      - :reference_number
      - :id
    - ActiveRecord::SessionStore::Session: 
      - data
    - Category: 
      - :permalink
      - :name
      - :parent_id
      - children_count
      - :id
      - parent_id
- home_index_get_public: 
    :format: text/html
    :method: :get
    :action: index
    :controller: home
    :is_public: true
    :models: 
    - Caresheet: 
      - :name
    - Order: 
      - tax
      - reference_number
      - :reference_number
      - updated_at
      - :state
      - id
      - amount
      - :updated_at
      - shipping
      - :created_at
      - user_id
      - subtotal
      - line_items_count
      - :id
      - created_at
      - state
      - ip_address
    - Category: 
      - :permalink
      - :name
      - :parent_id
      - children_count
      - :id
      - parent_id
    - Product: 
      - :description
      - :name
      - :permalink
      - :id
    - ActiveRecord::SessionStore::Session: 
      - session_id
    - Announcement: 
      - :body_short
      - :permalink
      - :id
      - :title_short
- static_show_get_public: 
    :format: text/html
    :method: :get
    :action: show
    :controller: static
    :is_public: true
    :models: 
    - Order: 
      - tax
      - reference_number
      - updated_at
      - :reference_number
      - :state
      - id
      - amount
      - :updated_at
      - shipping
      - :created_at
      - user_id
      - subtotal
      - line_items_count
      - :id
      - created_at
      - state
      - ip_address
    - Category: 
      - :permalink
      - :name
      - :parent_id
      - children_count
      - :id
      - parent_id
    - ActiveRecord::SessionStore::Session: 
      - data
- categories_show_get_public: 
    :format: text/html
    :method: :get
    :action: show
    :controller: categories
    :is_public: true
    :models: 
    - Order: 
      - :reference_number
      - :id
    - ActiveRecord::SessionStore::Session: 
      - data
    - Product: 
      - :price
      - :name
      - :permalink
      - :created_at
      - :id
      - :scientific_name
    - Category: 
      - :starting_price
      - :permalink
      - :name
      - :parent_id
      - children_count
      - :is_price_specific
      - parent_id
      - :id
